service: dictation-backend

provider:
  name: aws
  environment:
    DYNAMODB_ENDPOINT: http://localhost:8000

plugins:
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    host: 0.0.0.0
  dynamodb:
    start:
      port: 8000
      inMemory: false
      dbPath: ./db
      migrate: true

functions:
  register:
    handler: src/functions/register.handler
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: src/functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  list:
    handler: src/functions/file/list.handler
    events:
      - http:
          path: files
          method: get
          cors: true
  upload:
    handler: src/functions/file/upload.handler
    events:
      - http:
          path: files/upload
          method: post
          cors: true
  delete:
    handler: src/functions/file/delete.handler
    events:
      - http:
          path: files/delete/{id}
          method: delete
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dictation-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dictation-files
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL